minio:
  endpoint: http://localhost:9000
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: my-bucket
  secure: false

server:
  port: 8080



spring:
  application:
    name: demo
